
# url: "https://eliottvincent.github.io" # the base hostname & protocol for the site

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Personal

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: huipingr@usc.edu
      link: huipingr@usc.edu

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed
